const SPRITE = {
  // ========== 玩家職業 ==========
  warrior: { 
    idle: 'assets/warrior/idle.png',
    walk: 'assets/warrior/walk.png',
    walk2: 'assets/warrior/walk2.png',
    walk3: 'assets/warrior/walk3.png',
    walk4: 'assets/warrior/walk4.png',
    attack: 'assets/warrior/attack.png',
    attack2: 'assets/warrior/attack2.png',
    hit: 'assets/warrior/hit.png',
    color: '#c03020', glow: '#ff7040', useImg: true,
    multiFrame: true, // 启用多帧动画
    coverMode: true, // 使用 object-fit:cover 显示竖版图
    slashColor: '#ffd880',
  },
  mage: {
    idle: 'assets/mage/idle.png',
    walk: 'assets/mage/walk.png',
    walk2: 'assets/mage/walk2.png',
    walk3: 'assets/mage/walk3.png',
    walk4: 'assets/mage/walk4.png',
    attack: 'assets/mage/attack.png',
    attack2: 'assets/mage/attack2.png',
    hit: 'assets/mage/hit.png',
    color: '#8040c0', glow: '#c080ff', useImg: true,
    multiFrame: true, coverMode: true,
    slashColor: '#80c0ff',
  },
  archer: {
    idle: 'assets/archer/idle.png',
    walk: 'assets/archer/walk.png',
    walk2: 'assets/archer/walk2.png',
    walk3: 'assets/archer/walk3.png',
    walk4: 'assets/archer/walk4.png',
    attack: 'assets/archer/attack.png',
    attack2: 'assets/archer/attack2.png',
    hit: 'assets/archer/hit.png',
    color: '#408040', glow: '#80c060', useImg: true,
    multiFrame: true, coverMode: true,
    slashColor: '#a0ff80',
  },
  rogue: {
    idle: 'assets/rogue/idle.png',
    walk: 'assets/rogue/walk.png',
    walk2: 'assets/rogue/walk2.png',
    walk3: 'assets/rogue/walk3.png',
    walk4: 'assets/rogue/walk4.png',
    attack: 'assets/rogue/attack.png',
    attack2: 'assets/rogue/attack2.png',
    hit: 'assets/rogue/hit.png',
    color: '#602030', glow: '#a04060', useImg: true,
    multiFrame: true, coverMode: true,
    slashColor: '#ff6060',
  },
  paladin: {
    idle: 'assets/paladin/idle.png',
    walk: 'assets/paladin/walk.png',
    walk2: 'assets/paladin/walk2.png',
    walk3: 'assets/paladin/walk3.png',
    walk4: 'assets/paladin/walk4.png',
    attack: 'assets/paladin/attack.png',
    attack2: 'assets/paladin/attack2.png',
    hit: 'assets/paladin/hit.png',
    color: '#e0c060', glow: '#fff0a0', useImg: true,
    multiFrame: true, coverMode: true,
    slashColor: '#ffffff',
  },
  warlock: {
    idle: '/spark/app/app_17ch22wujxs/runtime/api/v1/storage/object/bucket_aadkq5g4dkmew_static/static%2Faadkrd2udyyco_ve_miaoda',
    attack: '/spark/app/app_17ch22wujxs/runtime/api/v1/storage/object/bucket_aadkq5g4dkmew_static/static%2Faadkrd2udyyco_ve_miaoda',
    color: '#602080', glow: '#a060e0', useImg: true
  },
  // ========== 變身形態（8幀完整動畫） ==========
  // ---------- 金色神話 ----------
  death_knight: {
    idle: 'https://aka.doubaocdn.com/s/sZCb8OB6bL',
    walk: 'https://aka.doubaocdn.com/s/sZCb8OB6bL',
    walk2: 'https://aka.doubaocdn.com/s/kjXnwP6c6Q',
    walk3: 'https://aka.doubaocdn.com/s/9L5kJRdXkU',
    walk4: 'https://aka.doubaocdn.com/s/GsVeRxnwhk',
    attack: 'https://aka.doubaocdn.com/s/95MOzrPXE4',
    attack2: 'https://aka.doubaocdn.com/s/5V9228QzVY',
    hit: 'https://aka.doubaocdn.com/s/QUmDnQmu2V',
    color: '#2a2030', glow: '#60ff60', useImg: true,
    multiFrame: true, coverMode: true,
    slashColor: '#60ff80',
  },
  ishti: {
    idle: 'https://aka.doubaocdn.com/s/3bD1z9o8eg',
    walk: 'https://aka.doubaocdn.com/s/3bD1z9o8eg',
    walk2: 'https://aka.doubaocdn.com/s/Bb4unEW6Or',
    walk3: 'https://aka.doubaocdn.com/s/5qCBEK1sLt',
    walk4: 'https://aka.doubaocdn.com/s/PblYU3LYWK',
    attack: 'https://aka.doubaocdn.com/s/IVTvgZd0UQ',
    attack2: 'https://aka.doubaocdn.com/s/LPEiyQx9Rw',
    hit: 'https://aka.doubaocdn.com/s/tYgMztu4TJ',
    color: '#508070', glow: '#80d0b0', useImg: true,
    multiFrame: true, coverMode: true,
    slashColor: '#a0ffd0',
  },
  reya: {
    idle: 'https://aka.doubaocdn.com/s/fyAgs0rT2U',
    walk: 'https://aka.doubaocdn.com/s/fyAgs0rT2U',
    walk2: 'https://aka.doubaocdn.com/s/ipvu758c68',
    walk3: 'https://aka.doubaocdn.com/s/rUNpaVcNTV',
    walk4: 'https://aka.doubaocdn.com/s/JopDfIOw63',
    attack: 'https://aka.doubaocdn.com/s/JXKMtQDjka',
    attack2: 'https://aka.doubaocdn.com/s/teo6Rq0FDT',
    hit: 'https://aka.doubaocdn.com/s/twKeG7UsnN',
    color: '#402030', glow: '#ff70a0', useImg: true,
    multiFrame: true, coverMode: true,
    slashColor: '#ff90c0',
  },
  baphomet: {
    idle: 'https://aka.doubaocdn.com/s/8KOIwItpMd',
    walk: 'https://aka.doubaocdn.com/s/8KOIwItpMd',
    walk2: 'https://aka.doubaocdn.com/s/IRN6nMGdEI',
    walk3: 'https://aka.doubaocdn.com/s/TzCUCDhjcu',
    walk4: 'https://aka.doubaocdn.com/s/6PUkZUgPkd',
    attack: 'https://aka.doubaocdn.com/s/nYsO49hDwZ',
    attack2: 'https://aka.doubaocdn.com/s/p930ZQKLDY',
    hit: 'https://aka.doubaocdn.com/s/JktTBAZnKa',
    color: '#501060', glow: '#c060ff', useImg: true,
    multiFrame: true, coverMode: true,
    slashColor: '#c080ff',
  },
  // ---------- 紫色傳說 ----------
  demon_hunter: {
    idle: 'https://aka.doubaocdn.com/s/X25020KITK',
    walk: 'https://aka.doubaocdn.com/s/X25020KITK',
    walk2: 'https://aka.doubaocdn.com/s/cUjFPtZ0qW',
    walk3: 'https://aka.doubaocdn.com/s/tVVnum1RHF',
    walk4: 'https://aka.doubaocdn.com/s/UNXOnnvtkr',
    attack: 'https://aka.doubaocdn.com/s/oDD0P2I05N',
    attack2: 'https://aka.doubaocdn.com/s/oDD0P2I05N',
    hit: 'https://aka.doubaocdn.com/s/libIUSPFdr',
    color: '#701a1a', glow: '#e04040', useImg: true,
    multiFrame: true, coverMode: true,
    slashColor: '#ff8060',
  },
  illusionist: {
    idle: 'https://aka.doubaocdn.com/s/hkUGU9PcrJ',
    walk: 'https://aka.doubaocdn.com/s/hkUGU9PcrJ',
    walk2: 'https://aka.doubaocdn.com/s/8hLX21hIX7',
    walk3: 'https://aka.doubaocdn.com/s/VIhy8YlPG3',
    walk4: 'https://aka.doubaocdn.com/s/fo7IkKOdCV',
    attack: 'https://aka.doubaocdn.com/s/DQ2zKd6PlE',
    attack2: 'https://aka.doubaocdn.com/s/DQ2zKd6PlE',
    hit: 'https://aka.doubaocdn.com/s/ymSWLgEVKA',
    color: '#6040a0', glow: '#a080ff', useImg: true,
    multiFrame: true, coverMode: true,
    slashColor: '#c0a0ff',
  },
  anubis: {
    idle: 'https://aka.doubaocdn.com/s/MD0YV0uUp3',
    walk: 'https://aka.doubaocdn.com/s/MD0YV0uUp3',
    walk2: 'https://aka.doubaocdn.com/s/77Di514UHF',
    walk3: 'https://aka.doubaocdn.com/s/UHhTcjVpkB',
    walk4: 'https://aka.doubaocdn.com/s/EesMLrHMPq',
    attack: 'https://aka.doubaocdn.com/s/qzfRRcBskj',
    attack2: 'https://aka.doubaocdn.com/s/qzfRRcBskj',
    hit: 'https://aka.doubaocdn.com/s/hFbVk7Wv8K',
    color: '#303020', glow: '#e0c060', useImg: true,
    multiFrame: true, coverMode: true,
    slashColor: '#ffd880',
  },
  chaos_knight: {
    idle: 'https://aka.doubaocdn.com/s/ZOAUXTCkwq',
    walk: 'https://aka.doubaocdn.com/s/ZOAUXTCkwq',
    walk2: 'https://aka.doubaocdn.com/s/sXiSWjgOUW',
    walk3: 'https://aka.doubaocdn.com/s/1mwrtdUjUW',
    walk4: 'https://aka.doubaocdn.com/s/EVisbZLQtX',
    attack: 'https://aka.doubaocdn.com/s/fOknq8rtA6',
    attack2: 'https://aka.doubaocdn.com/s/tIU5IOjXsC',
    hit: 'https://aka.doubaocdn.com/s/pr2EY6HfKb',
    color: '#302030', glow: '#a04060', useImg: true,
    multiFrame: true, coverMode: true,
    slashColor: '#c06060',
  },
  shadow_assassin: {
    idle: 'https://aka.doubaocdn.com/s/iY86u9q36V',
    walk: 'https://aka.doubaocdn.com/s/iY86u9q36V',
    walk2: 'https://aka.doubaocdn.com/s/IgQ8xDV3U4',
    walk3: 'https://aka.doubaocdn.com/s/3qi2k1tCkD',
    walk4: 'https://aka.doubaocdn.com/s/VMWbMkUyXH',
    attack: 'https://aka.doubaocdn.com/s/L0GFiAC4BR',
    attack2: 'https://aka.doubaocdn.com/s/xpE72e816U',
    hit: 'https://aka.doubaocdn.com/s/JHRLHgLeB7',
    color: '#202030', glow: '#6060a0', useImg: true,
    multiFrame: true, coverMode: true,
    slashColor: '#8080d0',
  },
  holy_envoy: {
    idle: 'https://aka.doubaocdn.com/s/UZK9QQSG8O',
    walk: 'https://aka.doubaocdn.com/s/UZK9QQSG8O',
    walk2: 'https://aka.doubaocdn.com/s/Qph4YNxnpW',
    walk3: 'https://aka.doubaocdn.com/s/IpcEagfwmT',
    walk4: 'https://aka.doubaocdn.com/s/aNZwWxt8wX',
    attack: 'https://aka.doubaocdn.com/s/VQQHfjBleU',
    attack2: 'https://aka.doubaocdn.com/s/Ffq0Ozp9WT',
    hit: 'https://aka.doubaocdn.com/s/WJDNaGLHAt',
    color: '#c0a040', glow: '#fff0a0', useImg: true,
    multiFrame: true, coverMode: true,
    slashColor: '#ffffff',
  },
  divine_envoy: {
    idle: 'https://aka.doubaocdn.com/s/K5xHlNU28s',
    walk: 'https://aka.doubaocdn.com/s/K5xHlNU28s',
    walk2: 'https://aka.doubaocdn.com/s/tfleZSU2QM',
    walk3: 'https://aka.doubaocdn.com/s/XqAIeRurL0',
    walk4: 'https://aka.doubaocdn.com/s/tyr9eGSGRp',
    attack: 'https://aka.doubaocdn.com/s/8neMJjtvhr',
    attack2: 'https://aka.doubaocdn.com/s/FizXHwVIDs',
    hit: 'https://aka.doubaocdn.com/s/NsjVkvEGJF',
    color: '#d0c080', glow: '#fff8c0', useImg: true,
    multiFrame: true, coverMode: true,
    slashColor: '#fff8d0',
  },
  // ---------- 紅色史詩 ----------
  balrog: {
    idle: 'https://aka.doubaocdn.com/s/tdkg3als9P',
    walk: 'https://aka.doubaocdn.com/s/tdkg3als9P',
    walk2: 'https://aka.doubaocdn.com/s/K9NBB7cGSb',
    walk3: 'https://aka.doubaocdn.com/s/YzTgNSPMxr',
    walk4: 'https://aka.doubaocdn.com/s/a9s53qaahR',
    attack: 'https://aka.doubaocdn.com/s/s88OAtsBTM',
    attack2: 'https://aka.doubaocdn.com/s/UkrwvfPntT',
    hit: 'https://aka.doubaocdn.com/s/rU1ioEhNRd',
    color: '#601010', glow: '#ff6030', useImg: true,
    multiFrame: true, coverMode: true,
    slashColor: '#ff9040',
  },
  dark_knight_red: {
    idle: 'https://aka.doubaocdn.com/s/MGWIDhAmHM',
    walk: 'https://aka.doubaocdn.com/s/MGWIDhAmHM',
    walk2: 'https://aka.doubaocdn.com/s/dr9VJVQW76',
    walk3: 'https://aka.doubaocdn.com/s/tjZe2VQqCV',
    walk4: 'https://aka.doubaocdn.com/s/i4rVzQcOe5',
    attack: 'https://aka.doubaocdn.com/s/BODZUpyXSI',
    attack2: 'https://aka.doubaocdn.com/s/je8dqUMZZI',
    hit: 'https://aka.doubaocdn.com/s/nqcRUI3qJU',
    color: '#201028', glow: '#ff3030', useImg: true,
    multiFrame: true, coverMode: true,
    slashColor: '#ff4040',
  },
  dark_mage_red: {
    idle: 'https://aka.doubaocdn.com/s/zrnCCihNJt',
    walk: 'https://aka.doubaocdn.com/s/zrnCCihNJt',
    walk2: 'https://aka.doubaocdn.com/s/BiBfVufViZ',
    walk3: 'https://aka.doubaocdn.com/s/nIVWCJVzvT',
    walk4: 'https://aka.doubaocdn.com/s/kfSS24e8lc',
    attack: 'https://aka.doubaocdn.com/s/YifczyXetY',
    attack2: 'https://aka.doubaocdn.com/s/DCr5DPCmxk',
    hit: 'https://aka.doubaocdn.com/s/CRvwT4vtVx',
    color: '#300040', glow: '#c040ff', useImg: true,
    multiFrame: true, coverMode: true,
    slashColor: '#d060ff',
  },
  dark_sorcerer: {
    idle: 'https://aka.doubaocdn.com/s/gZssWp0Yaq',
    walk: 'https://aka.doubaocdn.com/s/gZssWp0Yaq',
    walk2: 'https://aka.doubaocdn.com/s/iTVLHzirHU',
    walk3: 'https://aka.doubaocdn.com/s/FfzUQzcUjH',
    walk4: 'https://aka.doubaocdn.com/s/Ni2RrhDZ1j',
    attack: 'https://aka.doubaocdn.com/s/8hb1wWKeFd',
    attack2: 'https://aka.doubaocdn.com/s/yzizeV2vZe',
    hit: 'https://aka.doubaocdn.com/s/9j6fRyQNOL',
    color: '#401050', glow: '#ff50c0', useImg: true,
    multiFrame: true, coverMode: true,
    slashColor: '#ff80d0',
  },
  dark_assassin_red: {
    idle: 'https://aka.doubaocdn.com/s/ZOURHhq9xO',
    walk: 'https://aka.doubaocdn.com/s/ZOURHhq9xO',
    walk2: 'https://aka.doubaocdn.com/s/8UiDnbHq3e',
    walk3: 'https://aka.doubaocdn.com/s/UGv0OG7wbW',
    walk4: 'https://aka.doubaocdn.com/s/KXQqHrFfFL',
    attack: 'https://aka.doubaocdn.com/s/EIpWEIeVMj',
    attack2: 'https://aka.doubaocdn.com/s/WaGtGiouSs',
    hit: 'https://aka.doubaocdn.com/s/9dOsER3iAQ',
    color: '#101018', glow: '#ff2060', useImg: true,
    multiFrame: true, coverMode: true,
    slashColor: '#ff4080',
  },
  ghost_archer: {
    idle: 'https://aka.doubaocdn.com/s/P9nRBRY0yz',
    walk: 'https://aka.doubaocdn.com/s/P9nRBRY0yz',
    walk2: 'https://aka.doubaocdn.com/s/3jWWxnd4sb',
    walk3: 'https://aka.doubaocdn.com/s/T6U5hG7RQH',
    walk4: 'https://aka.doubaocdn.com/s/X6JwwPTJvv',
    attack: 'https://aka.doubaocdn.com/s/Z6uaGG4xJS',
    attack2: 'https://aka.doubaocdn.com/s/oqrXlRj3Z5',
    hit: 'https://aka.doubaocdn.com/s/AKVEuZjd4f',
    color: '#203040', glow: '#60c0ff', useImg: true,
    multiFrame: true, coverMode: true,
    slashColor: '#80e0ff',
  },
  silver_knight_galahad: {
    idle: 'https://aka.doubaocdn.com/s/LEtxcl2amQ',
    walk: 'https://aka.doubaocdn.com/s/LEtxcl2amQ',
    walk2: 'https://aka.doubaocdn.com/s/1BinCuwimp',
    walk3: 'https://aka.doubaocdn.com/s/vaVKLURbXq',
    walk4: 'https://aka.doubaocdn.com/s/VlwJcbZBZg',
    attack: 'https://aka.doubaocdn.com/s/c2pcXyCAoC',
    attack2: 'https://aka.doubaocdn.com/s/UBsEfc2hXx',
    hit: 'https://aka.doubaocdn.com/s/MwmmkPb6gf',
    color: '#c0c0e0', glow: '#fff0a0', useImg: true,
    multiFrame: true, coverMode: true,
    slashColor: '#ffffff',
  },

  // ---------- 藍色稀有（新變身） ----------
  frost_knight: {
    idle: 'https://aka.doubaocdn.com/s/AXY4DIQe2G',
    walk: 'https://aka.doubaocdn.com/s/AXY4DIQe2G',
    walk2: 'https://aka.doubaocdn.com/s/G3QcnMpuCP',
    walk3: 'https://aka.doubaocdn.com/s/ef7gCUKojx',
    walk4: 'https://aka.doubaocdn.com/s/KfG4vGHfBg',
    attack: 'https://aka.doubaocdn.com/s/F9QCsN3SUJ',
    attack2: 'https://aka.doubaocdn.com/s/DagRO0Zu0O',
    hit: 'https://aka.doubaocdn.com/s/GP2tFT10gV',
    color: '#204060', glow: '#60c0ff', useImg: true,
    multiFrame: true, coverMode: true,
    slashColor: '#80d0ff',
  },
  berserker_blue: {
    idle: 'https://aka.doubaocdn.com/s/WoJbCl806L',
    walk: 'https://aka.doubaocdn.com/s/WoJbCl806L',
    walk2: 'https://aka.doubaocdn.com/s/lJuFzWMxAU',
    walk3: 'https://aka.doubaocdn.com/s/0behWSGxwq',
    walk4: 'https://aka.doubaocdn.com/s/hZVlq8jqks',
    attack: 'https://aka.doubaocdn.com/s/il72r9FzSj',
    attack2: 'https://aka.doubaocdn.com/s/D6U5t601Rd',
    hit: 'https://aka.doubaocdn.com/s/RuWfBBWE3q',
    color: '#304060', glow: '#70a0ff', useImg: true,
    multiFrame: true, coverMode: true,
    slashColor: '#90b0ff',
  },
  frost_mage: {
    idle: 'https://aka.doubaocdn.com/s/5S1tUIsls4',
    walk: 'https://aka.doubaocdn.com/s/5S1tUIsls4',
    walk2: 'https://aka.doubaocdn.com/s/4im8YcndVt',
    walk3: 'https://aka.doubaocdn.com/s/yavRrKoSfb',
    walk4: 'https://aka.doubaocdn.com/s/MwULW9MFX6',
    attack: 'https://aka.doubaocdn.com/s/OncrG5zfYk',
    attack2: 'https://aka.doubaocdn.com/s/J9PLJTHNOp',
    hit: 'https://aka.doubaocdn.com/s/4FHggRV3UL',
    color: '#203060', glow: '#80c0ff', useImg: true,
    multiFrame: true, coverMode: true,
    slashColor: '#a0d0ff',
  },
  lightning_mage: {
    idle: 'https://aka.doubaocdn.com/s/Ke1R2tYyYi',
    walk: 'https://aka.doubaocdn.com/s/Ke1R2tYyYi',
    walk2: 'https://aka.doubaocdn.com/s/i9ohDah6fK',
    walk3: 'https://aka.doubaocdn.com/s/1yaLUBo60m',
    walk4: 'https://aka.doubaocdn.com/s/Jf0iOCYab0',
    attack: 'https://aka.doubaocdn.com/s/qdmsMhWgqS',
    attack2: 'https://aka.doubaocdn.com/s/vnhVMY1Mbl',
    hit: 'https://aka.doubaocdn.com/s/zZYmJKREfl',
    color: '#302060', glow: '#a080ff', useImg: true,
    multiFrame: true, coverMode: true,
    slashColor: '#b090ff',
  },
  elf_archer_blue: {
    idle: 'https://aka.doubaocdn.com/s/DA1JiUu25C',
    walk: 'https://aka.doubaocdn.com/s/DA1JiUu25C',
    walk2: 'https://aka.doubaocdn.com/s/mKkn8z5w9j',
    walk3: 'https://aka.doubaocdn.com/s/QzBWNKPsY4',
    walk4: 'https://aka.doubaocdn.com/s/boUCARKlUK',
    attack: 'https://aka.doubaocdn.com/s/uzOCokO05x',
    attack2: 'https://aka.doubaocdn.com/s/L2mcusQPUi',
    hit: 'https://aka.doubaocdn.com/s/lVvCMQkXCa',
    color: '#205060', glow: '#60e0d0', useImg: true,
    multiFrame: true, coverMode: true,
    slashColor: '#80f0e0',
  },
  wind_walker: {
    idle: 'https://aka.doubaocdn.com/s/A9YN2hiCuY',
    walk: 'https://aka.doubaocdn.com/s/A9YN2hiCuY',
    walk2: 'https://aka.doubaocdn.com/s/BxhqoNBsy9',
    walk3: 'https://aka.doubaocdn.com/s/DInQE4sGfT',
    walk4: 'https://aka.doubaocdn.com/s/k5L5nRvfAz',
    attack: 'https://aka.doubaocdn.com/s/RPBVhIBi7V',
    attack2: 'https://aka.doubaocdn.com/s/RPBVhIBi7V',
    hit: 'https://aka.doubaocdn.com/s/A9YN2hiCuY',
    color: '#206040', glow: '#80e0a0', useImg: true,
    multiFrame: true, coverMode: true,
    slashColor: '#a0f0c0',
  },
  silver_knight_blue: {
    idle: 'https://aka.doubaocdn.com/s/wLT8tzjGBp',
    walk: 'https://aka.doubaocdn.com/s/wLT8tzjGBp',
    walk2: 'https://aka.doubaocdn.com/s/YxXoXhdLmS',
    walk3: 'https://aka.doubaocdn.com/s/cN3E5Nquah',
    walk4: 'https://aka.doubaocdn.com/s/ci6rXRx8DG',
    attack: 'https://aka.doubaocdn.com/s/OSap9erVl0',
    attack2: 'https://aka.doubaocdn.com/s/QRytegQ1Oe',
    hit: 'https://aka.doubaocdn.com/s/JIGsfqs5tQ',
    color: '#c0c0d8', glow: '#e0e8ff', useImg: true,
    multiFrame: true, coverMode: true,
    slashColor: '#f0f0ff',
  },
  temple_knight: {
    idle: 'https://aka.doubaocdn.com/s/nPAX4om6CQ',
    walk: 'https://aka.doubaocdn.com/s/nPAX4om6CQ',
    walk2: 'https://aka.doubaocdn.com/s/72qwU65Xsa',
    walk3: 'https://aka.doubaocdn.com/s/UNCvpUlZe3',
    walk4: 'https://aka.doubaocdn.com/s/BG9V2u0zRc',
    attack: 'https://aka.doubaocdn.com/s/IVxWqYtCFv',
    attack2: 'https://aka.doubaocdn.com/s/9aJxLBlYSk',
    hit: 'https://aka.doubaocdn.com/s/bSTo2dlMbK',
    color: '#d0c080', glow: '#ffe8a0', useImg: true,
    multiFrame: true, coverMode: true,
    slashColor: '#fff0c0',
  },
  shadow_assassin_blue: {
    idle: 'https://aka.doubaocdn.com/s/cRVH78jrX4',
    walk: 'https://aka.doubaocdn.com/s/cRVH78jrX4',
    walk2: 'https://aka.doubaocdn.com/s/owA0PPIkhb',
    walk3: 'https://aka.doubaocdn.com/s/rCn1Xg8QwR',
    walk4: 'https://aka.doubaocdn.com/s/QO6k6TReK3',
    attack: 'https://aka.doubaocdn.com/s/uiC3MCWbCM',
    attack2: 'https://aka.doubaocdn.com/s/3E5L92SGX8',
    hit: 'https://aka.doubaocdn.com/s/FEaYTU3HUH',
    color: '#202030', glow: '#6080c0', useImg: true,
    multiFrame: true, coverMode: true,
    slashColor: '#80a0e0',
  },
  poison_blade: {
    idle: 'https://aka.doubaocdn.com/s/qRmnQyhsHF',
    walk: 'https://aka.doubaocdn.com/s/qRmnQyhsHF',
    walk2: 'https://aka.doubaocdn.com/s/IIMkBDTmaj',
    walk3: 'https://aka.doubaocdn.com/s/RBtLFeKz3n',
    walk4: 'https://aka.doubaocdn.com/s/StSWxwsuyL',
    attack: 'https://aka.doubaocdn.com/s/uQMK2b8OQV',
    attack2: 'https://aka.doubaocdn.com/s/DEI5Znr00s',
    hit: 'https://aka.doubaocdn.com/s/mO6nx6RVMn',
    color: '#204020', glow: '#80d060', useImg: true,
    multiFrame: true, coverMode: true,
    slashColor: '#a0e080',
  },
  gargoyle: {
    idle: 'https://aka.doubaocdn.com/s/Qz5xkyMung',
    walk: 'https://aka.doubaocdn.com/s/Qz5xkyMung',
    walk2: 'https://aka.doubaocdn.com/s/SiOQl1qSHv',
    walk3: 'https://aka.doubaocdn.com/s/FXdRQ4zYcV',
    walk4: 'https://aka.doubaocdn.com/s/kgBNXt4Xoo',
    attack: 'https://aka.doubaocdn.com/s/vQNYtfo6e9',
    attack2: 'https://aka.doubaocdn.com/s/gLa19G08zS',
    hit: 'https://aka.doubaocdn.com/s/PABlGUtHZI',
    color: '#404050', glow: '#a0a0c0', useImg: true,
    multiFrame: true, coverMode: true,
    slashColor: '#c0c0d0',
  },
  werewolf: {
    idle: 'https://aka.doubaocdn.com/s/GMxsqLaCGt',
    walk: 'https://aka.doubaocdn.com/s/GMxsqLaCGt',
    walk2: 'https://aka.doubaocdn.com/s/q3MAJiktJq',
    walk3: 'https://aka.doubaocdn.com/s/P8x4odPP2g',
    walk4: 'https://aka.doubaocdn.com/s/xipd7571LS',
    attack: 'https://aka.doubaocdn.com/s/qaasdrxeR4',
    attack2: 'https://aka.doubaocdn.com/s/Z3K4JEOsj7',
    hit: 'https://aka.doubaocdn.com/s/khEwYymEiA',
    color: '#503020', glow: '#c08060', useImg: true,
    multiFrame: true, coverMode: true,
    slashColor: '#e0a080',
  },

  // ---------- 綠色精良（新變身） ----------
  forest_guardian: {
    idle: 'https://aka.doubaocdn.com/s/1daCVmkSeg',
    walk: 'https://aka.doubaocdn.com/s/1daCVmkSeg',
    walk2: 'https://aka.doubaocdn.com/s/7rkggQtVva',
    walk3: 'https://aka.doubaocdn.com/s/7EMmttpXtt',
    walk4: 'https://aka.doubaocdn.com/s/rUD0POkJta',
    attack: 'https://aka.doubaocdn.com/s/rFGDkDOZRB',
    attack2: 'https://aka.doubaocdn.com/s/0yfRk9msfe',
    hit: 'https://aka.doubaocdn.com/s/u8C4FDxAzq',
    color: '#205030', glow: '#60c080', useImg: true,
    multiFrame: true, coverMode: true,
    slashColor: '#80e0a0',
  },
  wind_spirit: {
    idle: 'https://aka.doubaocdn.com/s/jkm5kDZZyi',
    walk: 'https://aka.doubaocdn.com/s/jkm5kDZZyi',
    walk2: 'https://aka.doubaocdn.com/s/s1b9NsVUNP',
    walk3: 'https://aka.doubaocdn.com/s/rY6t9P8rRQ',
    walk4: 'https://aka.doubaocdn.com/s/u5eemtHJJk',
    attack: 'https://aka.doubaocdn.com/s/Vn6NQ5HTfP',
    attack2: 'https://aka.doubaocdn.com/s/C3VstdT6dQ',
    hit: 'https://aka.doubaocdn.com/s/n7NjzUEXzg',
    color: '#80c0c0', glow: '#c0f0f0', useImg: true,
    multiFrame: true, coverMode: true,
    slashColor: '#e0ffff',
  },
  green_dragon: {
    idle: 'https://aka.doubaocdn.com/s/Pl4PBEqsvs',
    walk: 'https://aka.doubaocdn.com/s/Pl4PBEqsvs',
    walk2: 'https://aka.doubaocdn.com/s/CH3Wf8rqcv',
    walk3: 'https://aka.doubaocdn.com/s/324delxMNK',
    walk4: 'https://aka.doubaocdn.com/s/jsmfG7UE6X',
    attack: 'https://aka.doubaocdn.com/s/StVW9D5cG3',
    attack2: 'https://aka.doubaocdn.com/s/KGGg348qE0',
    hit: 'https://aka.doubaocdn.com/s/lyhUAf9LY1',
    color: '#204020', glow: '#80d060', useImg: true,
    multiFrame: true, coverMode: true,
    slashColor: '#a0e080',
  },
  druid: {
    idle: 'https://aka.doubaocdn.com/s/g5u2Sq5agH',
    walk: 'https://aka.doubaocdn.com/s/g5u2Sq5agH',
    walk2: 'https://aka.doubaocdn.com/s/8uoto9Z1wj',
    walk3: 'https://aka.doubaocdn.com/s/y1G12v4mDa',
    walk4: 'https://aka.doubaocdn.com/s/3eq3rAYEYV',
    attack: 'https://aka.doubaocdn.com/s/pFJT2Xc5o8',
    attack2: 'https://aka.doubaocdn.com/s/Qd4BJClvxa',
    hit: 'https://aka.doubaocdn.com/s/UdeJSiOwgC',
    color: '#405020', glow: '#a0c060', useImg: true,
    multiFrame: true, coverMode: true,
    slashColor: '#c0e080',
  },
  treant: {
    idle: 'https://aka.doubaocdn.com/s/BIuGGAsYZh',
    walk: 'https://aka.doubaocdn.com/s/BIuGGAsYZh',
    walk2: 'https://aka.doubaocdn.com/s/vlURIemaSk',
    walk3: 'https://aka.doubaocdn.com/s/GI7RvSykGX',
    walk4: 'https://aka.doubaocdn.com/s/RqzkY6gSAe',
    attack: 'https://aka.doubaocdn.com/s/q2rm4wKK3M',
    attack2: 'https://aka.doubaocdn.com/s/F6ctRUeEtA',
    hit: 'https://aka.doubaocdn.com/s/fNqR5LHWx6',
    color: '#403020', glow: '#80a050', useImg: true,
    multiFrame: true, coverMode: true,
    slashColor: '#a0c070',
  },

  // ---------- 白色普通（新變身） ----------
  white_dragon: {
    idle: 'https://aka.doubaocdn.com/s/APDWUGWZVw',
    walk: 'https://aka.doubaocdn.com/s/APDWUGWZVw',
    walk2: 'https://aka.doubaocdn.com/s/bYD7aJdZCZ',
    walk3: 'https://aka.doubaocdn.com/s/EHH32Fvnw1',
    walk4: 'https://aka.doubaocdn.com/s/01wfNPiTXP',
    attack: 'https://aka.doubaocdn.com/s/PL5FOn3oK3',
    attack2: 'https://aka.doubaocdn.com/s/UfxwzeARpf',
    hit: 'https://aka.doubaocdn.com/s/UIynvopITS',
    color: '#e0e8f0', glow: '#ffffff', useImg: true,
    multiFrame: true, coverMode: true,
    slashColor: '#ffffff',
  },
  angel_white: {
    idle: 'https://aka.doubaocdn.com/s/NaPbNp9c1V',
    walk: 'https://aka.doubaocdn.com/s/NaPbNp9c1V',
    walk2: 'https://aka.doubaocdn.com/s/GUlp5Qy6iw',
    walk3: 'https://aka.doubaocdn.com/s/5UMFE65Hny',
    walk4: 'https://aka.doubaocdn.com/s/hbuS4nnQI2',
    attack: 'https://aka.doubaocdn.com/s/0UZceLNR6V',
    attack2: 'https://aka.doubaocdn.com/s/kUFVQVjTCS',
    hit: 'https://aka.doubaocdn.com/s/3ygE66VdLj',
    color: '#f0f0e8', glow: '#fff8c0', useImg: true,
    multiFrame: true, coverMode: true,
    slashColor: '#ffffff',
  },
  unicorn: {
    idle: 'https://aka.doubaocdn.com/s/a8JCQmVVNT',
    walk: 'https://aka.doubaocdn.com/s/a8JCQmVVNT',
    walk2: 'https://aka.doubaocdn.com/s/f8JFmtkifj',
    walk3: 'https://aka.doubaocdn.com/s/8dvXmhS5c7',
    walk4: 'https://aka.doubaocdn.com/s/HzkkhZbJQy',
    attack: 'https://aka.doubaocdn.com/s/FOIte0Nrnl',
    attack2: 'https://aka.doubaocdn.com/s/2lE46ur5Jl',
    hit: 'https://aka.doubaocdn.com/s/1OVUePiezR',
    color: '#f8f0f8', glow: '#ffe0ff', useImg: true,
    multiFrame: true, coverMode: true,
    slashColor: '#ffffff',
  },
  holy_spirit: {
    idle: 'https://aka.doubaocdn.com/s/TLuUdtTRPo',
    walk: 'https://aka.doubaocdn.com/s/TLuUdtTRPo',
    walk2: 'https://aka.doubaocdn.com/s/JcezH6rVhY',
    walk3: 'https://aka.doubaocdn.com/s/gnxhj1r7Tr',
    walk4: 'https://aka.doubaocdn.com/s/8IDPqcesFo',
    attack: 'https://aka.doubaocdn.com/s/aNWVrFpkQ7',
    attack2: 'https://aka.doubaocdn.com/s/DGdNzHjEpE',
    hit: 'https://aka.doubaocdn.com/s/wZ2LHv5DEE',
    color: '#e8f0f8', glow: '#c0e0ff', useImg: true,
    multiFrame: true, coverMode: true,
    slashColor: '#f0f8ff',
  },
  white_wolf: {
    idle: 'https://aka.doubaocdn.com/s/dPBulifvdn',
    walk: 'https://aka.doubaocdn.com/s/dPBulifvdn',
    walk2: 'https://aka.doubaocdn.com/s/vtUUJB7bTi',
    walk3: 'https://aka.doubaocdn.com/s/Atwxnpfckc',
    walk4: 'https://aka.doubaocdn.com/s/ysMOfAVZc0',
    attack: 'https://aka.doubaocdn.com/s/tjFKwAE5pk',
    attack2: 'https://aka.doubaocdn.com/s/ekiTVHnUBx',
    hit: 'https://aka.doubaocdn.com/s/ohKPiheUuX',
    color: '#d8d8e0', glow: '#e8e8f0', useImg: true,
    multiFrame: true, coverMode: true,
    slashColor: '#f0f0f8',
  },

  // ========== 怪物 ==========
  goblin: {
    idle: 'https://aka.doubaocdn.com/s/wYFHmKE2C0',
    walk: 'https://aka.doubaocdn.com/s/wYFHmKE2C0',
    walk2: 'https://aka.doubaocdn.com/s/UG1LXPgLYT',
    walk3: 'https://aka.doubaocdn.com/s/FVLNAE1Aju',
    walk4: 'https://aka.doubaocdn.com/s/nGscTgMw4F',
    attack: 'https://aka.doubaocdn.com/s/qN3FcGwEbv',
    attack2: 'https://aka.doubaocdn.com/s/ic8EWNDNYs',
    hit: 'https://aka.doubaocdn.com/s/WpaQwxUXzh',
    color: '#508040', glow: '#80c060', useImg: true,
    multiFrame: true, coverMode: true,
    slashColor: '#c0ff80',
  },
  skeleton: {
    idle: 'https://aka.doubaocdn.com/s/Wzi9iVLdb2',
    walk: 'https://aka.doubaocdn.com/s/Wzi9iVLdb2',
    walk2: 'https://aka.doubaocdn.com/s/U9ed5silDc',
    walk3: 'https://aka.doubaocdn.com/s/wpc6V9qVDO',
    walk4: 'https://aka.doubaocdn.com/s/1x1j3NjhPH',
    attack: 'https://aka.doubaocdn.com/s/VfGgZRdHIL',
    attack2: 'https://aka.doubaocdn.com/s/YQCgkX79ZB',
    hit: 'https://aka.doubaocdn.com/s/6ifL3DgjCY',
    color: '#e0e0d0', glow: '#ffffff', useImg: true,
    multiFrame: true, coverMode: true,
    slashColor: '#e0f0ff',
  },
  orc: {
    idle: 'https://aka.doubaocdn.com/s/7jZBWui3Db',
    walk: 'https://aka.doubaocdn.com/s/7jZBWui3Db',
    walk2: 'https://aka.doubaocdn.com/s/Zpc82edK6V',
    walk3: 'https://aka.doubaocdn.com/s/CewMfMo7tU',
    walk4: 'https://aka.doubaocdn.com/s/9Us5kQk4ie',
    attack: 'https://aka.doubaocdn.com/s/rvAT3NSnQB',
    attack2: 'https://aka.doubaocdn.com/s/5oTzfOrfzV',
    hit: 'https://aka.doubaocdn.com/s/Xc1HGJ1KGV',
    color: '#608040', glow: '#a0c060', useImg: true,
    multiFrame: true, coverMode: true,
    slashColor: '#d0ffa0',
  },
  slime: {
    idle: 'https://aka.doubaocdn.com/s/582Ij09o3K',
    walk: 'https://aka.doubaocdn.com/s/582Ij09o3K',
    walk2: 'https://aka.doubaocdn.com/s/hjTKkz0REl',
    walk3: 'https://aka.doubaocdn.com/s/uUcl6ZXFlt',
    walk4: 'https://aka.doubaocdn.com/s/naY3bow36j',
    attack: 'https://aka.doubaocdn.com/s/Wi8i3HuMPN',
    attack2: 'https://aka.doubaocdn.com/s/xWZWQAzLLU',
    hit: 'https://aka.doubaocdn.com/s/ULQRvB1CdS',
    color: '#40a060', glow: '#80e0a0', useImg: true,
    multiFrame: true, coverMode: true,
    slashColor: '#a0ffc0',
  },
  spider: {
    idle: 'https://aka.doubaocdn.com/s/6AohjTIRnR',
    walk: 'https://aka.doubaocdn.com/s/6AohjTIRnR',
    walk2: 'https://aka.doubaocdn.com/s/AKCLMYp49L',
    walk3: 'https://aka.doubaocdn.com/s/2hMO5hilVu',
    walk4: 'https://aka.doubaocdn.com/s/L5TZ5ntmcZ',
    attack: 'https://aka.doubaocdn.com/s/P4IKJKFaPb',
    attack2: 'https://aka.doubaocdn.com/s/jrdjr24uAs',
    hit: 'https://aka.doubaocdn.com/s/IkB3kC0MLn',
    color: '#402020', glow: '#804040', useImg: true,
    multiFrame: true, coverMode: true,
    slashColor: '#ff6060',
  },
  scorpion: {
    idle: '/spark/app/app_17ch22wujxs/runtime/api/v1/storage/object/bucket_aadkq5g4dkmew_static/static%2Faadkreacgyqdo_ve_miaoda',
    color: '#a06020', glow: '#ff9040', useImg: true
  },
  bat: {
    idle: '/spark/app/app_17ch22wujxs/runtime/api/v1/storage/object/bucket_aadkq5g4dkmew_static/static%2Faadkrd25ssaao_ve_miaoda',
    color: '#604060', glow: '#a080c0', useImg: true
  },
  monsterwolf: {
    idle: '/spark/app/app_17ch22wujxs/runtime/api/v1/storage/object/bucket_aadkq5g4dkmew_static/static%2Faadkrd7rqfobi_ve_miaoda',
    attack: '/spark/app/app_17ch22wujxs/runtime/api/v1/storage/object/bucket_aadkq5g4dkmew_static/static%2Faadkrd7rqfobi_ve_miaoda',
    color: '#505060', glow: '#a0a0c0', useImg: true
  },
  ghost: {
    idle: '/spark/app/app_17ch22wujxs/runtime/api/v1/storage/object/bucket_aadkq5g4dkmew_static/static%2Faadkread3d2eg_ve_miaoda',
    color: '#a0b0d0', glow: '#d0e0f0', useImg: true
  },
  troll: {
    idle: '/spark/app/app_17ch22wujxs/runtime/api/v1/storage/object/bucket_aadkq5g4dkmew_static/static%2Faadkreb7m4ibg_ve_miaoda',
    color: '#608040', glow: '#90c060', useImg: true
  },
  demon: {
    idle: 'https://aka.doubaocdn.com/s/ennzdff10h',
    walk: 'https://aka.doubaocdn.com/s/ennzdff10h',
    walk2: 'https://aka.doubaocdn.com/s/HHYnZL77dr',
    walk3: 'https://aka.doubaocdn.com/s/iA3sODRZZ1',
    walk4: 'https://aka.doubaocdn.com/s/iovh4nWNY3',
    attack: 'https://aka.doubaocdn.com/s/VvBW6MiFDv',
    attack2: 'https://aka.doubaocdn.com/s/GCjQ9UYJCa',
    hit: 'https://aka.doubaocdn.com/s/bOvayC2iOD',
    color: '#c03030', glow: '#ff6040', useImg: true,
    multiFrame: true, coverMode: true,
    slashColor: '#ff5050',
  },
  // 中高階怪物 8 帧
  ogre: {
    idle: 'https://aka.doubaocdn.com/s/6mcEV2Pgpy',
    walk: 'https://aka.doubaocdn.com/s/6mcEV2Pgpy',
    walk2: 'https://aka.doubaocdn.com/s/OlcaeodfWk',
    walk3: 'https://aka.doubaocdn.com/s/EfvFkRDFHo',
    walk4: 'https://aka.doubaocdn.com/s/8s0noOL4Yj',
    attack: 'https://aka.doubaocdn.com/s/WV9nboUyMl',
    attack2: 'https://aka.doubaocdn.com/s/YY8fAAd1go',
    hit: 'https://aka.doubaocdn.com/s/5vqHZHGQV5',
    color: '#806040', glow: '#d0a060', useImg: true,
    multiFrame: true, coverMode: true,
    slashColor: '#ffb060',
  },
  lizardman: {
    idle: 'https://aka.doubaocdn.com/s/TCEkPooI9E',
    walk: 'https://aka.doubaocdn.com/s/TCEkPooI9E',
    walk2: 'https://aka.doubaocdn.com/s/S4gNP4k3pT',
    walk3: 'https://aka.doubaocdn.com/s/AY9mkXA71v',
    walk4: 'https://aka.doubaocdn.com/s/HLDhc9wPmh',
    attack: 'https://aka.doubaocdn.com/s/w9OpsvrH9Z',
    attack2: 'https://aka.doubaocdn.com/s/3iG0uaSQjw',
    hit: 'https://aka.doubaocdn.com/s/rmIJxJ5Fpg',
    color: '#40a060', glow: '#80e0a0', useImg: true,
    multiFrame: true, coverMode: true,
    slashColor: '#a0ffc0',
  },
  stone_golem: {
    idle: 'https://aka.doubaocdn.com/s/1djiUtrb2c',
    walk: 'https://aka.doubaocdn.com/s/1djiUtrb2c',
    walk2: 'https://aka.doubaocdn.com/s/znvzkueF2c',
    walk3: 'https://aka.doubaocdn.com/s/Ix5C2VbmyJ',
    walk4: 'https://aka.doubaocdn.com/s/pVW3CEoidZ',
    attack: 'https://aka.doubaocdn.com/s/38FuwV7gPw',
    attack2: 'https://aka.doubaocdn.com/s/BUQtrrYRAS',
    hit: 'https://aka.doubaocdn.com/s/paWYrtkpSB',
    color: '#908070', glow: '#c0b0a0', useImg: true,
    multiFrame: true, coverMode: true,
    slashColor: '#e0d0b0',
  },
  lich: {
    idle: 'https://aka.doubaocdn.com/s/DKPorAcX7s',
    walk: 'https://aka.doubaocdn.com/s/DKPorAcX7s',
    walk2: 'https://aka.doubaocdn.com/s/RiirQZ3fSV',
    walk3: 'https://aka.doubaocdn.com/s/MuVRCBrUzD',
    walk4: 'https://aka.doubaocdn.com/s/iQg6zyogEa',
    attack: 'https://aka.doubaocdn.com/s/JspSNdIB2O',
    attack2: 'https://aka.doubaocdn.com/s/A2ZjoB2Pki',
    hit: 'https://aka.doubaocdn.com/s/OgVGjrT6k0',
    color: '#8040a0', glow: '#c080e0', useImg: true,
    multiFrame: true, coverMode: true,
    slashColor: '#e0a0ff',
  },
  cerberus: {
    idle: 'https://aka.doubaocdn.com/s/F8IHeapTW8',
    walk: 'https://aka.doubaocdn.com/s/F8IHeapTW8',
    walk2: 'https://aka.doubaocdn.com/s/jCmgvBVpIR',
    walk3: 'https://aka.doubaocdn.com/s/hLV7TMIaDa',
    walk4: 'https://aka.doubaocdn.com/s/88U5UCP6GP',
    attack: 'https://aka.doubaocdn.com/s/GfUTUL5jbI',
    attack2: 'https://aka.doubaocdn.com/s/En7HDFOJVa',
    hit: 'https://aka.doubaocdn.com/s/QdZmXT0MUR',
    color: '#a02020', glow: '#ff5030', useImg: true,
    multiFrame: true, coverMode: true,
    slashColor: '#ff6040',
  },
  dragon: {
    idle: '/spark/app/app_17ch22wujxs/runtime/api/v1/storage/object/bucket_aadkq5g4dkmew_static/static%2Faadkreacphggg_ve_miaoda',
    attack: '/spark/app/app_17ch22wujxs/runtime/api/v1/storage/object/bucket_aadkq5g4dkmew_static/static%2Faadkreacphggg_ve_miaoda',
    color: '#d08020', glow: '#ffb060', useImg: true
  },
  shaman: {
    idle: '/spark/app/app_17ch22wujxs/runtime/api/v1/storage/object/bucket_aadkq5g4dkmew_static/static%2Faadkrd7t3t6ko_ve_miaoda',
    attack: '/spark/app/app_17ch22wujxs/runtime/api/v1/storage/object/bucket_aadkq5g4dkmew_static/static%2Faadkrd7t3t6ko_ve_miaoda',
    color: '#608040', glow: '#90c060', useImg: true
  },
  bandit: {
    idle: '/spark/app/app_17ch22wujxs/runtime/api/v1/storage/object/bucket_aadkq5g4dkmew_static/static%2Faadkrd4brrcsq_ve_miaoda',
    attack: '/spark/app/app_17ch22wujxs/runtime/api/v1/storage/object/bucket_aadkq5g4dkmew_static/static%2Faadkrd4brrcsq_ve_miaoda',
    color: '#804020', glow: '#c08040', useImg: true
  },
  zombie: {
    idle: '/spark/app/app_17ch22wujxs/runtime/api/v1/storage/object/bucket_aadkq5g4dkmew_static/static%2Faadkrd3b5jgii_ve_miaoda',
    attack: '/spark/app/app_17ch22wujxs/runtime/api/v1/storage/object/bucket_aadkq5g4dkmew_static/static%2Faadkrd3b5jgii_ve_miaoda',
    color: '#608060', glow: '#90b080', useImg: true
  },
  darkmage: {
    idle: '/spark/app/app_17ch22wujxs/runtime/api/v1/storage/object/bucket_aadkq5g4dkmew_static/static%2Faadkreacxtmgg_ve_miaoda',
    attack: '/spark/app/app_17ch22wujxs/runtime/api/v1/storage/object/bucket_aadkq5g4dkmew_static/static%2Faadkreacxtmgg_ve_miaoda',
    color: '#6040a0', glow: '#a080e0', useImg: true
  },
  // ========== Boss ==========
  boss_goblin:  { idle: '👺', attack: '💥', color: '#a04020', glow: '#ff7040', boss: true },
  boss_troll:   { idle: '👹', attack: '💥', color: '#608040', glow: '#90c060', boss: true },
  boss_lich:    { idle: '💀', attack: '✨', color: '#8040a0', glow: '#c080e0', boss: true },
  boss_scorpion:{ idle: '🦂', attack: '💥', color: '#a06020', glow: '#d09040', boss: true },
  boss_bat:     { idle: '🦇', attack: '💥', color: '#802040', glow: '#ff4060', boss: true },
  boss_orc:     { idle: '👹', attack: '💥', color: '#a04020', glow: '#ff7040', boss: true },
  boss_ghost:   { idle: '👻', attack: '💀', color: '#6060a0', glow: '#a0a0ff', boss: true },
  boss_demon:   { idle: '😈', attack: '🔥', color: '#c02020', glow: '#ff5050', boss: true },
  boss_dragon:  { idle: '🐉', attack: '💥', color: '#e09010', glow: '#ffc040', boss: true },
  shaman: {
    idle: '/spark/app/app_17ch22wujxs/runtime/api/v1/storage/object/bucket_aadkq5g4dkmew_static/static%2Faadkrbyz6ssai_ve_miaoda',
    attack: '/spark/app/app_17ch22wujxs/runtime/api/v1/storage/object/bucket_aadkq5g4dkmew_static/static%2Faadkrbyz6ssai_ve_miaoda',
    color: '#608040', glow: '#90c060', useImg: true
  },
  bandit: {
    idle: '/spark/app/app_17ch22wujxs/runtime/api/v1/storage/object/bucket_aadkq5g4dkmew_static/static%2Faadkrb2g4hwbq_ve_miaoda',
    attack: '/spark/app/app_17ch22wujxs/runtime/api/v1/storage/object/bucket_aadkq5g4dkmew_static/static%2Faadkrb2g4hwbq_ve_miaoda',
    color: '#804020', glow: '#c08040', useImg: true
  },
  zombie: {
    idle: '/spark/app/app_17ch22wujxs/runtime/api/v1/storage/object/bucket_aadkq5g4dkmew_static/static%2Faadkrb2trecbq_ve_miaoda',
    attack: '/spark/app/app_17ch22wujxs/runtime/api/v1/storage/object/bucket_aadkq5g4dkmew_static/static%2Faadkrb2trecbq_ve_miaoda',
    color: '#608060', glow: '#90b080', useImg: true
  },
  darkmage: {
    idle: '/spark/app/app_17ch22wujxs/runtime/api/v1/storage/object/bucket_aadkq5g4dkmew_static/static%2Faadkrbyu7xcag_ve_miaoda',
    attack: '/spark/app/app_17ch22wujxs/runtime/api/v1/storage/object/bucket_aadkq5g4dkmew_static/static%2Faadkrbyu7xcag_ve_miaoda',
    color: '#6040a0', glow: '#a080e0', useImg: true
  },
  // ========== Boss ==========
  boss_goblin: {
    idle: '/spark/app/app_17ch22wujxs/runtime/api/v1/storage/object/bucket_aadkq5g4dkmew_static/static%2Faadkreeyoo6hq_ve_miaoda',
    attack: '/spark/app/app_17ch22wujxs/runtime/api/v1/storage/object/bucket_aadkq5g4dkmew_static/static%2Faadkreeyoo6hq_ve_miaoda',
    color: '#a04020', glow: '#ff7040', boss: true, useImg: true
  },
  boss_troll: {
    idle: '/spark/app/app_17ch22wujxs/runtime/api/v1/storage/object/bucket_aadkq5g4dkmew_static/static%2Faadkreb7m4ibg_ve_miaoda',
    attack: '/spark/app/app_17ch22wujxs/runtime/api/v1/storage/object/bucket_aadkq5g4dkmew_static/static%2Faadkreb7m4ibg_ve_miaoda',
    color: '#608040', glow: '#90c060', boss: true, useImg: true
  },
  boss_lich: {
    idle: '/spark/app/app_17ch22wujxs/runtime/api/v1/storage/object/bucket_aadkq5g4dkmew_static/static%2Faadkredbr4oeo_ve_miaoda',
    attack: '/spark/app/app_17ch22wujxs/runtime/api/v1/storage/object/bucket_aadkq5g4dkmew_static/static%2Faadkredbr4oeo_ve_miaoda',
    color: '#8040a0', glow: '#c080e0', boss: true, useImg: true
  },
  boss_scorpion: {
    idle: '/spark/app/app_17ch22wujxs/runtime/api/v1/storage/object/bucket_aadkq5g4dkmew_static/static%2Faadkreacgyqdo_ve_miaoda',
    attack: '/spark/app/app_17ch22wujxs/runtime/api/v1/storage/object/bucket_aadkq5g4dkmew_static/static%2Faadkreacgyqdo_ve_miaoda',
    color: '#a06020', glow: '#d09040', boss: true, useImg: true
  },
  boss_bat: {
    idle: '/spark/app/app_17ch22wujxs/runtime/api/v1/storage/object/bucket_aadkq5g4dkmew_static/static%2Faadkrd25ssaao_ve_miaoda',
    attack: '/spark/app/app_17ch22wujxs/runtime/api/v1/storage/object/bucket_aadkq5g4dkmew_static/static%2Faadkrd25ssaao_ve_miaoda',
    color: '#802040', glow: '#ff4060', boss: true, useImg: true
  },
  boss_orc: {
    idle: '/spark/app/app_17ch22wujxs/runtime/api/v1/storage/object/bucket_aadkq5g4dkmew_static/static%2Faadkrd3d7j6pq_ve_miaoda',
    attack: '/spark/app/app_17ch22wujxs/runtime/api/v1/storage/object/bucket_aadkq5g4dkmew_static/static%2Faadkrd3d7j6pq_ve_miaoda',
    color: '#a04020', glow: '#ff7040', boss: true, useImg: true
  },
  boss_ghost: {
    idle: '/spark/app/app_17ch22wujxs/runtime/api/v1/storage/object/bucket_aadkq5g4dkmew_static/static%2Faadkread3d2eg_ve_miaoda',
    attack: '/spark/app/app_17ch22wujxs/runtime/api/v1/storage/object/bucket_aadkq5g4dkmew_static/static%2Faadkread3d2eg_ve_miaoda',
    color: '#6060a0', glow: '#a0a0ff', boss: true, useImg: true
  },
  boss_demon: {
    idle: '/spark/app/app_17ch22wujxs/runtime/api/v1/storage/object/bucket_aadkq5g4dkmew_static/static%2Faadkreezckefq_ve_miaoda',
    attack: '/spark/app/app_17ch22wujxs/runtime/api/v1/storage/object/bucket_aadkq5g4dkmew_static/static%2Faadkreezckefq_ve_miaoda',
    color: '#c02020', glow: '#ff5050', boss: true, useImg: true
  },
  boss_dragon: {
    idle: 'https://aka.doubaocdn.com/s/o1qWUrCATh',
    walk: 'https://aka.doubaocdn.com/s/o1qWUrCATh',
    walk2: 'https://aka.doubaocdn.com/s/g3Irrwx4oq',
    walk3: 'https://aka.doubaocdn.com/s/jJaVDoXIZ2',
    walk4: 'https://aka.doubaocdn.com/s/CnUAPsRzlA',
    attack: 'https://aka.doubaocdn.com/s/Fr4eqGqBd6',
    attack2: 'https://aka.doubaocdn.com/s/mXwLa8wNlS',
    hit: 'https://aka.doubaocdn.com/s/1wgGAVd8JU',
    color: '#e09010', glow: '#ffc040', boss: true, useImg: true,
    multiFrame: true, coverMode: true,
    slashColor: '#ffd060',
  },
  boss_death_knight: {
    idle: 'https://aka.doubaocdn.com/s/7FnWRqmp3O',
    walk: 'https://aka.doubaocdn.com/s/7FnWRqmp3O',
    walk2: 'https://aka.doubaocdn.com/s/U8U8zD5mQY',
    walk3: 'https://aka.doubaocdn.com/s/x0ngk7iSES',
    walk4: 'https://aka.doubaocdn.com/s/aPOtgxIgss',
    attack: 'https://aka.doubaocdn.com/s/KRVgdmZdqh',
    attack2: 'https://aka.doubaocdn.com/s/B1oZEnBt4W',
    hit: 'https://aka.doubaocdn.com/s/eqsOwvfx7E',
    color: '#404060', glow: '#8080c0', boss: true, useImg: true,
    multiFrame: true, coverMode: true,
    slashColor: '#c0c0ff',
  },
  boss_baphomet: {
    idle: 'https://aka.doubaocdn.com/s/B5UzjmgzgT',
    walk: 'https://aka.doubaocdn.com/s/B5UzjmgzgT',
    walk2: 'https://aka.doubaocdn.com/s/rCZVzIR4DM',
    walk3: 'https://aka.doubaocdn.com/s/DsZs2wdjX8',
    walk4: 'https://aka.doubaocdn.com/s/FvmW2tQuUr',
    attack: 'https://aka.doubaocdn.com/s/fXcREvAk5H',
    attack2: 'https://aka.doubaocdn.com/s/49gZhlUxoM',
    hit: 'https://aka.doubaocdn.com/s/9aUL4o7j9K',
    color: '#602040', glow: '#ff5080', boss: true, useImg: true,
    multiFrame: true, coverMode: true,
    slashColor: '#ff80a0',
  },
  boss_demon_lord: {
    idle: 'https://aka.doubaocdn.com/s/MQbYJyKtqK',
    walk: 'https://aka.doubaocdn.com/s/MQbYJyKtqK',
    walk2: 'https://aka.doubaocdn.com/s/daKfmMOKiL',
    walk3: 'https://aka.doubaocdn.com/s/H0oH4yS5iQ',
    walk4: 'https://aka.doubaocdn.com/s/HfzbqxNOUp',
    attack: 'https://aka.doubaocdn.com/s/wltQkklEoZ',
    attack2: 'https://aka.doubaocdn.com/s/OYdq2KLrpQ',
    hit: 'https://aka.doubaocdn.com/s/7YUd2dOZDc',
    color: '#a01010', glow: '#ff3030', boss: true, useImg: true,
    multiFrame: true, coverMode: true,
    slashColor: '#ff5050',
  },
  // ========== NPC ==========
  // ========== NPC 8 幀完整動畫 ==========
  npc_blacksmith: {
    idle: 'https://aka.doubaocdn.com/s/dTOA2QKqa8',
    walk: 'https://aka.doubaocdn.com/s/dTOA2QKqa8',
    walk2: 'https://aka.doubaocdn.com/s/JiW0xwVu7J',
    walk3: 'https://aka.doubaocdn.com/s/JUMDNgMWNh',
    walk4: 'https://aka.doubaocdn.com/s/eNrCqbW21z',
    attack: 'https://aka.doubaocdn.com/s/miiDBxtyiq',
    attack2: 'https://aka.doubaocdn.com/s/839Tu3fbmo',
    hit: 'https://aka.doubaocdn.com/s/joG7wQ5Okj',
    color: '#c08040', glow: '#ffc080', npc: true, useImg: true, multiFrame: true,
  },
  npc_shop: {
    idle: 'https://aka.doubaocdn.com/s/PllNPKAjDG',
    walk: 'https://aka.doubaocdn.com/s/PllNPKAjDG',
    walk2: 'https://aka.doubaocdn.com/s/lX6cLQIs6s',
    walk3: 'https://aka.doubaocdn.com/s/GhtUV9MoUM',
    walk4: 'https://aka.doubaocdn.com/s/1pMUj0WrTL',
    attack: 'https://aka.doubaocdn.com/s/oAdyWKiLsb',
    attack2: 'https://aka.doubaocdn.com/s/i3hZlyVOEh',
    hit: 'https://aka.doubaocdn.com/s/boDlZxOnVq',
    color: '#a08060', glow: '#d0b080', npc: true, useImg: true, multiFrame: true,
  },
  npc_luxury: {
    idle: 'https://aka.doubaocdn.com/s/SzFME3Pi9q',
    walk: 'https://aka.doubaocdn.com/s/SzFME3Pi9q',
    walk2: 'https://aka.doubaocdn.com/s/GmJMM0gLrk',
    walk3: 'https://aka.doubaocdn.com/s/2ZqpOZV4JY',
    walk4: 'https://aka.doubaocdn.com/s/Vy3TpO90sn',
    attack: 'https://aka.doubaocdn.com/s/KUmdX94cVK',
    attack2: 'https://aka.doubaocdn.com/s/lcRLg7RtoR',
    hit: 'https://aka.doubaocdn.com/s/nvZ2iSN7Wz',
    color: '#b080c0', glow: '#e0b0ff', npc: true, useImg: true, multiFrame: true,
  },
  npc_warehouse: {
    idle: 'https://aka.doubaocdn.com/s/8UYlKPr8L4',
    walk: 'https://aka.doubaocdn.com/s/8UYlKPr8L4',
    walk2: 'https://aka.doubaocdn.com/s/VgfWfm7Wp3',
    walk3: 'https://aka.doubaocdn.com/s/NPqYADvHxg',
    walk4: 'https://aka.doubaocdn.com/s/Buiu25AfYt',
    attack: 'https://aka.doubaocdn.com/s/YBZ4yf3Kz5',
    attack2: 'https://aka.doubaocdn.com/s/BBZwu283Gy',
    hit: 'https://aka.doubaocdn.com/s/1HbZreUQHQ',
    color: '#a08060', glow: '#d0b080', npc: true, useImg: true, multiFrame: true,
  },
  npc_quest: {
    idle: 'https://aka.doubaocdn.com/s/Cv17QVXyT5',
    walk: 'https://aka.doubaocdn.com/s/Cv17QVXyT5',
    walk2: 'https://aka.doubaocdn.com/s/4srtvDjQPd',
    walk3: 'https://aka.doubaocdn.com/s/UlhVkekfia',
    walk4: 'https://aka.doubaocdn.com/s/B1Xj8KAEhe',
    attack: 'https://aka.doubaocdn.com/s/IrrsDh0lJh',
    attack2: 'https://aka.doubaocdn.com/s/oe0oox3tFe',
    hit: 'https://aka.doubaocdn.com/s/ADErARCdEu',
    color: '#4080c0', glow: '#80b0ff', npc: true, useImg: true, multiFrame: true,
  },
  npc_inn: {
    idle: 'https://aka.doubaocdn.com/s/9nqQW8OMjO',
    walk: 'https://aka.doubaocdn.com/s/9nqQW8OMjO',
    walk2: 'https://aka.doubaocdn.com/s/LAPpVgy0XL',
    walk3: 'https://aka.doubaocdn.com/s/iXPfLZ7kDc',
    walk4: 'https://aka.doubaocdn.com/s/ccwUb4KD6L',
    attack: 'https://aka.doubaocdn.com/s/1LlR6vpGYg',
    attack2: 'https://aka.doubaocdn.com/s/5m99bxAUW8',
    hit: 'https://aka.doubaocdn.com/s/wQdrQVESaP',
    color: '#d06040', glow: '#ffa080', npc: true, useImg: true, multiFrame: true,
  },
  npc_priest: {
    idle: 'https://aka.doubaocdn.com/s/9nqQW8OMjO',
    walk: 'https://aka.doubaocdn.com/s/9nqQW8OMjO',
    walk2: 'https://aka.doubaocdn.com/s/LAPpVgy0XL',
    walk3: 'https://aka.doubaocdn.com/s/iXPfLZ7kDc',
    walk4: 'https://aka.doubaocdn.com/s/ccwUb4KD6L',
    attack: 'https://aka.doubaocdn.com/s/1LlR6vpGYg',
    attack2: 'https://aka.doubaocdn.com/s/5m99bxAUW8',
    hit: 'https://aka.doubaocdn.com/s/wQdrQVESaP',
    color: '#f0e0b0', glow: '#fff8d0', npc: true, useImg: true, multiFrame: true,
  },
  npc_dungeon: {
    idle: 'https://aka.doubaocdn.com/s/WQcx9I9OBq',
    walk: 'https://aka.doubaocdn.com/s/WQcx9I9OBq',
    walk2: 'https://aka.doubaocdn.com/s/ZNvUhqSGHj',
    walk3: 'https://aka.doubaocdn.com/s/kgmSkvojy6',
    walk4: 'https://aka.doubaocdn.com/s/TjaUWFvn6f',
    attack: 'https://aka.doubaocdn.com/s/T73arNQQlA',
    attack2: 'https://aka.doubaocdn.com/s/N3ukZgdVoy',
    hit: 'https://aka.doubaocdn.com/s/u8YESfQcD3',
    color: '#604080', glow: '#a080c0', npc: true, useImg: true, multiFrame: true,
  },
  npc_board: {
    idle: '/spark/app/app_17ch22wujxs/runtime/api/v1/storage/object/bucket_aadkq5g4dkmew_static/static%2Faadkrehajimao_ve_miaoda',
    color: '#806040', glow: '#c0a070', npc: true, useImg: true
  },
  npc_guard: {
    idle: 'https://aka.doubaocdn.com/s/TiXM8q4lZK',
    walk: 'https://aka.doubaocdn.com/s/TiXM8q4lZK',
    walk2: 'https://aka.doubaocdn.com/s/jjmrlmCWwC',
    walk3: 'https://aka.doubaocdn.com/s/8UCc4uRd5e',
    walk4: 'https://aka.doubaocdn.com/s/7x4aF7VXRK',
    attack: 'https://aka.doubaocdn.com/s/s8UUkfmEvx',
    attack2: 'https://aka.doubaocdn.com/s/qfwrYpaJ2K',
    hit: 'https://aka.doubaocdn.com/s/YZXtVvdmuR',
    color: '#a08050', glow: '#d0b070', npc: true, useImg: true, multiFrame: true,
  },
  npc_healer: {
    idle: 'https://aka.doubaocdn.com/s/9nqQW8OMjO',
    walk: 'https://aka.doubaocdn.com/s/9nqQW8OMjO',
    walk2: 'https://aka.doubaocdn.com/s/LAPpVgy0XL',
    walk3: 'https://aka.doubaocdn.com/s/iXPfLZ7kDc',
    walk4: 'https://aka.doubaocdn.com/s/ccwUb4KD6L',
    attack: 'https://aka.doubaocdn.com/s/1LlR6vpGYg',
    attack2: 'https://aka.doubaocdn.com/s/5m99bxAUW8',
    hit: 'https://aka.doubaocdn.com/s/wQdrQVESaP',
    color: '#f0e0b0', glow: '#fff8d0', npc: true, useImg: true, multiFrame: true,
  },
  npc_wizard: {
    idle: 'https://aka.doubaocdn.com/s/WQcx9I9OBq',
    walk: 'https://aka.doubaocdn.com/s/WQcx9I9OBq',
    walk2: 'https://aka.doubaocdn.com/s/ZNvUhqSGHj',
    walk3: 'https://aka.doubaocdn.com/s/kgmSkvojy6',
    walk4: 'https://aka.doubaocdn.com/s/TjaUWFvn6f',
    attack: 'https://aka.doubaocdn.com/s/T73arNQQlA',
    attack2: 'https://aka.doubaocdn.com/s/N3ukZgdVoy',
    hit: 'https://aka.doubaocdn.com/s/u8YESfQcD3',
    color: '#8060e0', glow: '#c0a0ff', npc: true, useImg: true, multiFrame: true,
  },
  // ========== 新英雄 8 幀完整動畫 ==========
  hero_fire_elemental: {
    idle: 'https://aka.doubaocdn.com/s/ScTVMscBly',
    walk: 'https://aka.doubaocdn.com/s/ScTVMscBly',
    walk2: 'https://aka.doubaocdn.com/s/CWImnq6w74',
    walk3: 'https://aka.doubaocdn.com/s/eGFznrB3mT',
    walk4: 'https://aka.doubaocdn.com/s/N9HEYzExfI',
    attack: 'https://aka.doubaocdn.com/s/DGju3Q4Ork',
    attack2: 'https://aka.doubaocdn.com/s/wF6kKJTc94',
    hit: 'https://aka.doubaocdn.com/s/drRUJ1PiSv',
    color: '#ff6030', glow: '#ffb060', useImg: true, multiFrame: true,
  },
  hero_frost_wolf: {
    idle: 'https://aka.doubaocdn.com/s/hvqAPvsE23',
    walk: 'https://aka.doubaocdn.com/s/hvqAPvsE23',
    walk2: 'https://aka.doubaocdn.com/s/crmYOmDoIP',
    walk3: 'https://aka.doubaocdn.com/s/5F14d71Pyl',
    walk4: 'https://aka.doubaocdn.com/s/wDBEVqyFld',
    attack: 'https://aka.doubaocdn.com/s/UhCMU18cUM',
    attack2: 'https://aka.doubaocdn.com/s/yPlesBoan0',
    hit: 'https://aka.doubaocdn.com/s/G5YNj7nOuU',
    color: '#60b0ff', glow: '#a0d8ff', useImg: true, multiFrame: true,
  },
  hero_dark_beast: {
    idle: 'https://aka.doubaocdn.com/s/l9oUjCLsvD',
    walk: 'https://aka.doubaocdn.com/s/l9oUjCLsvD',
    walk2: 'https://aka.doubaocdn.com/s/nO9v776UoV',
    walk3: 'https://aka.doubaocdn.com/s/2znmT3dKQc',
    walk4: 'https://aka.doubaocdn.com/s/r5SXmQVUv2',
    attack: 'https://aka.doubaocdn.com/s/4GGzWY67AP',
    attack2: 'https://aka.doubaocdn.com/s/XFdWB5oY1w',
    hit: 'https://aka.doubaocdn.com/s/IiUR2GRnKz',
    color: '#6040a0', glow: '#a080e0', useImg: true, multiFrame: true,
  },
  hero_golden_griffin: {
    idle: 'https://aka.doubaocdn.com/s/M8iLItb8SL',
    walk: 'https://aka.doubaocdn.com/s/M8iLItb8SL',
    walk2: 'https://aka.doubaocdn.com/s/emAq8UCONc',
    walk3: 'https://aka.doubaocdn.com/s/fCC7qVivRp',
    walk4: 'https://aka.doubaocdn.com/s/TAQamR2aH5',
    attack: 'https://aka.doubaocdn.com/s/3p1uOOFmcV',
    attack2: 'https://aka.doubaocdn.com/s/MouZcszF2k',
    hit: 'https://aka.doubaocdn.com/s/Ndq0gap6Nr',
    color: '#ffd040', glow: '#fff0a0', useImg: true, multiFrame: true,
  },
  hero_undead_knight: {
    idle: 'https://aka.doubaocdn.com/s/Zae7N0mwUb',
    walk: 'https://aka.doubaocdn.com/s/Zae7N0mwUb',
    walk2: 'https://aka.doubaocdn.com/s/pI0sXZsd8V',
    walk3: 'https://aka.doubaocdn.com/s/P5Zx8qWbOU',
    walk4: 'https://aka.doubaocdn.com/s/khiUoUYZ0t',
    attack: 'https://aka.doubaocdn.com/s/FdRbs6DDqD',
    attack2: 'https://aka.doubaocdn.com/s/wxUDxrtuLx',
    hit: 'https://aka.doubaocdn.com/s/oJot2AXiYN',
    color: '#a080d0', glow: '#d0b0ff', useImg: true, multiFrame: true,
  },
  hero_thunder_bear: {
    idle: 'https://aka.doubaocdn.com/s/Pq2UOQqKkD',
    walk: 'https://aka.doubaocdn.com/s/Pq2UOQqKkD',
    walk2: 'https://aka.doubaocdn.com/s/nYr4vtlMDr',
    walk3: 'https://aka.doubaocdn.com/s/RfAz4VpN1S',
    walk4: 'https://aka.doubaocdn.com/s/T9M88GBCQk',
    attack: 'https://aka.doubaocdn.com/s/jHVVvaUxZ2',
    attack2: 'https://aka.doubaocdn.com/s/Td3MQT1tnF',
    hit: 'https://aka.doubaocdn.com/s/U8qQhdSmbz',
    color: '#ffcc30', glow: '#ffee90', useImg: true, multiFrame: true,
  },
  hero_demoness: {
    idle: 'https://aka.doubaocdn.com/s/WawynjOGZK',
    walk: 'https://aka.doubaocdn.com/s/WawynjOGZK',
    walk2: 'https://aka.doubaocdn.com/s/dxmuWjHkBl',
    walk3: 'https://aka.doubaocdn.com/s/zfpTV9oMHP',
    walk4: 'https://aka.doubaocdn.com/s/x9J654XZVH',
    attack: 'https://aka.doubaocdn.com/s/paP684cHRG',
    attack2: 'https://aka.doubaocdn.com/s/znpkGtJ8yR',
    hit: 'https://aka.doubaocdn.com/s/oUwn28Nr9n',
    color: '#ff60a0', glow: '#ffa0d0', useImg: true, multiFrame: true,
  },
  hero_stone_titan: {
    idle: 'https://aka.doubaocdn.com/s/I2SNzCU0xy',
    walk: 'https://aka.doubaocdn.com/s/I2SNzCU0xy',
    walk2: 'https://aka.doubaocdn.com/s/zV8GhUB4Mx',
    walk3: 'https://aka.doubaocdn.com/s/YjCgRDLbqB',
    walk4: 'https://aka.doubaocdn.com/s/MVfdatmvBN',
    attack: 'https://aka.doubaocdn.com/s/axD7UXXItT',
    attack2: 'https://aka.doubaocdn.com/s/XrPTYEU4do',
    hit: 'https://aka.doubaocdn.com/s/Upf0cg83SP',
    color: '#a08060', glow: '#d0b080', useImg: true, multiFrame: true,
  },
  // ========== 英雄 ==========
  hero_knight: {
    idle: '/spark/app/app_17ch22wujxs/runtime/api/v1/storage/object/bucket_aadkq5g4dkmew_static/static%2Faadkrb2tol2gi_ve_miaoda',
    attack: '/spark/app/app_17ch22wujxs/runtime/api/v1/storage/object/bucket_aadkq5g4dkmew_static/static%2Faadkrb2tol2gi_ve_miaoda',
    color: '#c0a060', glow: '#ffe090', useImg: true
  },
  hero_archer: {
    idle: '/spark/app/app_17ch22wujxs/runtime/api/v1/storage/object/bucket_aadkq5g4dkmew_static/static%2Faadkrb2xfi6fq_ve_miaoda',
    attack: '/spark/app/app_17ch22wujxs/runtime/api/v1/storage/object/bucket_aadkq5g4dkmew_static/static%2Faadkrb2xfi6fq_ve_miaoda',
    color: '#60b060', glow: '#a0e090', useImg: true
  },
  hero_assassin: {
    idle: '/spark/app/app_17ch22wujxs/runtime/api/v1/storage/object/bucket_aadkq5g4dkmew_static/static%2Faadkrb2mtywho_ve_miaoda',
    attack: '/spark/app/app_17ch22wujxs/runtime/api/v1/storage/object/bucket_aadkq5g4dkmew_static/static%2Faadkrb2mtywho_ve_miaoda',
    color: '#a04060', glow: '#ff7090', useImg: true
  },
  // ========== 寵物 ==========
  pet_fox: {
    idle: '/spark/app/app_17ch22wujxs/runtime/api/v1/storage/object/bucket_aadkq5g4dkmew_static/static%2Faadkrefkve2fg_ve_miaoda',
    color: '#e06040', glow: '#ff9060', useImg: true
  },
  pet_wolf: {
    idle: '/spark/app/app_17ch22wujxs/runtime/api/v1/storage/object/bucket_aadkq5g4dkmew_static/static%2Faadkredgan6ag_ve_miaoda',
    color: '#a0a0c0', glow: '#c0e0ff', useImg: true
  },
  pet_rabbit: {
    idle: '/spark/app/app_17ch22wujxs/runtime/api/v1/storage/object/bucket_aadkq5g4dkmew_static/static%2Faadkreduxggio_ve_miaoda',
    color: '#f0c0e0', glow: '#ffe0f0', useImg: true
  },
  pet_cat: {
    idle: '/spark/app/app_17ch22wujxs/runtime/api/v1/storage/object/bucket_aadkq5g4dkmew_static/static%2Faadkregoykcfq_ve_miaoda',
    color: '#a08060', glow: '#d0b080', useImg: true
  },
  pet_crow: {
    idle: '/spark/app/app_17ch22wujxs/runtime/api/v1/storage/object/bucket_aadkq5g4dkmew_static/static%2Faadkreaq3qomg_ve_miaoda',
    color: '#8060a0', glow: '#c0a0e0', useImg: true
  },
  pet_fairy: {
    idle: '/spark/app/app_17ch22wujxs/runtime/api/v1/storage/object/bucket_aadkq5g4dkmew_static/static%2Faadkregzahuho_ve_miaoda',
    color: '#80e0a0', glow: '#c0ffd0', useImg: true
  },
  pet_phoenix: {
    idle: '/spark/app/app_17ch22wujxs/runtime/api/v1/storage/object/bucket_aadkq5g4dkmew_static/static%2Faadkrefq7fwai_ve_miaoda',
    color: '#ff6020', glow: '#ffa060', useImg: true
  },
  pet_wolf_ice: {
    idle: '/spark/app/app_17ch22wujxs/runtime/api/v1/storage/object/bucket_aadkq5g4dkmew_static/static%2Faadkrefmiwqlo_ve_miaoda',
    color: '#80c0e0', glow: '#c0e8ff', useImg: true
  },
  pet_unicorn: {
    idle: '/spark/app/app_17ch22wujxs/runtime/api/v1/storage/object/bucket_aadkq5g4dkmew_static/static%2Faadkreauduybg_ve_miaoda',
    color: '#f0e0ff', glow: '#fff0ff', useImg: true
  },
  pet_panther: {
    idle: '/spark/app/app_17ch22wujxs/runtime/api/v1/storage/object/bucket_aadkq5g4dkmew_static/static%2Faadkrebbrhgbg_ve_miaoda',
    color: '#603080', glow: '#a060d0', useImg: true
  },
  pet_thunder: {
    idle: '/spark/app/app_17ch22wujxs/runtime/api/v1/storage/object/bucket_aadkq5g4dkmew_static/static%2Faadkreelduido_ve_miaoda',
    color: '#f0e040', glow: '#fff890', useImg: true
  },
  pet_turtle: {
    idle: '/spark/app/app_17ch22wujxs/runtime/api/v1/storage/object/bucket_aadkq5g4dkmew_static/static%2Faadkrd7gxhmqi_ve_miaoda',
    color: '#60a060', glow: '#90d090', useImg: true
  },
  pet_tiger: {
    idle: '/spark/app/app_17ch22wujxs/runtime/api/v1/storage/object/bucket_aadkq5g4dkmew_static/static%2Faadkreerfeigo_ve_miaoda',
    color: '#e0a030', glow: '#ffd060', useImg: true
  },
  pet_panda: {
    idle: '/spark/app/app_17ch22wujxs/runtime/api/v1/storage/object/bucket_aadkq5g4dkmew_static/static%2Faadkrefkve2gg_ve_miaoda',
    color: '#606070', glow: '#b0b0c0', useImg: true
  },
  pet_dragon: {
    idle: '/spark/app/app_17ch22wujxs/runtime/api/v1/storage/object/bucket_aadkq5g4dkmew_static/static%2Faadkreerfeiho_ve_miaoda',
    color: '#e08030', glow: '#ffb060', useImg: true
  },
  pet_phoenix_legend: {
    idle: '/spark/app/app_17ch22wujxs/runtime/api/v1/storage/object/bucket_aadkq5g4dkmew_static/static%2Faadkregtzsyaq_ve_miaoda',
    color: '#ff6020', glow: '#ffa060', useImg: true
  },
  pet_dragon_legend: {
    idle: '/spark/app/app_17ch22wujxs/runtime/api/v1/storage/object/bucket_aadkq5g4dkmew_static/static%2Faadkrd6ajukei_ve_miaoda',
    color: '#d0a020', glow: '#ffe060', useImg: true
  },
  pet_ghost: {
    idle: '/spark/app/app_17ch22wujxs/runtime/api/v1/storage/object/bucket_aadkq5g4dkmew_static/static%2Faadkregzahugo_ve_miaoda',
    color: '#a0b0d0', glow: '#d0e0f0', useImg: true
  },
  pet_babydragon: {
    idle: '/spark/app/app_17ch22wujxs/runtime/api/v1/storage/object/bucket_aadkq5g4dkmew_static/static%2Faadkreb556oei_ve_miaoda',
    color: '#ff8030', glow: '#ffc060', useImg: true
  },
  pet_golddragon: {
    idle: '/spark/app/app_17ch22wujxs/runtime/api/v1/storage/object/bucket_aadkq5g4dkmew_static/static%2Faadkrd7ll3wai_ve_miaoda',
    color: '#ffd040', glow: '#fff080', useImg: true
  },
  // ========== 新寵物 8 幀完整動畫 ==========
  pet_imp: {
    idle: 'https://aka.doubaocdn.com/s/VNXoKs3gVe',
    walk: 'https://aka.doubaocdn.com/s/VNXoKs3gVe',
    walk2: 'https://aka.doubaocdn.com/s/8eUdSO7p1X',
    walk3: 'https://aka.doubaocdn.com/s/QgfE2yaV9i',
    walk4: 'https://aka.doubaocdn.com/s/UeNX99JezO',
    attack: 'https://aka.doubaocdn.com/s/aNnoxlZvqy',
    attack2: 'https://aka.doubaocdn.com/s/1kRVSk3VBo',
    hit: 'https://aka.doubaocdn.com/s/vm7NU2YYU2',
    color: '#ff8040', glow: '#ffb060', useImg: true, multiFrame: true,
  },
  pet_fairy_new: {
    idle: 'https://aka.doubaocdn.com/s/nhyoVvTDFa',
    walk: 'https://aka.doubaocdn.com/s/nhyoVvTDFa',
    walk2: 'https://aka.doubaocdn.com/s/OUOgvHV162',
    walk3: 'https://aka.doubaocdn.com/s/OS4DgGfxDX',
    walk4: 'https://aka.doubaocdn.com/s/UqBOwVpHVD',
    attack: 'https://aka.doubaocdn.com/s/gCnLxoD4bF',
    attack2: 'https://aka.doubaocdn.com/s/ZA02HOMe9o',
    hit: 'https://aka.doubaocdn.com/s/eGsb5rxWyJ',
    color: '#a0e0ff', glow: '#d0f0ff', useImg: true, multiFrame: true,
  },
  pet_witch_cat: {
    idle: 'https://aka.doubaocdn.com/s/QozCIYqTi6',
    walk: 'https://aka.doubaocdn.com/s/QozCIYqTi6',
    walk2: 'https://aka.doubaocdn.com/s/riDC4w2gn5',
    walk3: 'https://aka.doubaocdn.com/s/B3Q2VfQ2ma',
    walk4: 'https://aka.doubaocdn.com/s/34LTJLiNDO',
    attack: 'https://aka.doubaocdn.com/s/HSeduXVKKS',
    attack2: 'https://aka.doubaocdn.com/s/sDUTc8rRsH',
    hit: 'https://aka.doubaocdn.com/s/ywIBCICmss',
    color: '#a060e0', glow: '#c090ff', useImg: true, multiFrame: true,
  },
  pet_fire_lizard: {
    idle: 'https://aka.doubaocdn.com/s/3x3U48gZcR',
    walk: 'https://aka.doubaocdn.com/s/3x3U48gZcR',
    walk2: 'https://aka.doubaocdn.com/s/ZMuQtC5AnB',
    walk3: 'https://aka.doubaocdn.com/s/LDFdRSGLLU',
    walk4: 'https://aka.doubaocdn.com/s/9uCZT7XwV6',
    attack: 'https://aka.doubaocdn.com/s/Y0gKbBMsH0',
    attack2: 'https://aka.doubaocdn.com/s/KGHuzfmA1U',
    hit: 'https://aka.doubaocdn.com/s/hniEKvAlCO',
    color: '#ff5030', glow: '#ff9060', useImg: true, multiFrame: true,
  },
  pet_ice_sprite: {
    idle: 'https://aka.doubaocdn.com/s/bOtwklpRMp',
    walk: 'https://aka.doubaocdn.com/s/bOtwklpRMp',
    walk2: 'https://aka.doubaocdn.com/s/1pdxAdoLkk',
    walk3: 'https://aka.doubaocdn.com/s/t14WAYneux',
    walk4: 'https://aka.doubaocdn.com/s/fIErMbleyT',
    attack: 'https://aka.doubaocdn.com/s/6t4fhS2Rnk',
    attack2: 'https://aka.doubaocdn.com/s/0n0OP8HGwG',
    hit: 'https://aka.doubaocdn.com/s/OPGnviaSwV',
    color: '#60c0ff', glow: '#a0e0ff', useImg: true, multiFrame: true,
  },
  pet_ghost_new: {
    idle: 'https://aka.doubaocdn.com/s/rs4Pd5hKUV',
    walk: 'https://aka.doubaocdn.com/s/rs4Pd5hKUV',
    walk2: 'https://aka.doubaocdn.com/s/tVfIA7pfL5',
    walk3: 'https://aka.doubaocdn.com/s/vOdqBdV8SH',
    walk4: 'https://aka.doubaocdn.com/s/HqrXEGComg',
    attack: 'https://aka.doubaocdn.com/s/RDeqjGT7Vb',
    attack2: 'https://aka.doubaocdn.com/s/Hs525wcDUn',
    hit: 'https://aka.doubaocdn.com/s/CHsc86xPbU',
    color: '#c0c0e0', glow: '#e0e0ff', useImg: true, multiFrame: true,
  },
  pet_golden_whelp: {
    idle: 'https://aka.doubaocdn.com/s/0JFrRSWgEf',
    walk: 'https://aka.doubaocdn.com/s/0JFrRSWgEf',
    walk2: 'https://aka.doubaocdn.com/s/g7KBkTkxXR',
    walk3: 'https://aka.doubaocdn.com/s/7eH9UKyXCD',
    walk4: 'https://aka.doubaocdn.com/s/l8FG4zID55',
    attack: 'https://aka.doubaocdn.com/s/8vBBDoZ9zt',
    attack2: 'https://aka.doubaocdn.com/s/mbRbnIs048',
    hit: 'https://aka.doubaocdn.com/s/7A7eCh99EZ',
    color: '#ffd040', glow: '#ffee80', useImg: true, multiFrame: true,
  },
  pet_shadow_serpent: {
    idle: 'https://aka.doubaocdn.com/s/5chTx1jae1',
    walk: 'https://aka.doubaocdn.com/s/5chTx1jae1',
    walk2: 'https://aka.doubaocdn.com/s/5pLySnK3Lg',
    walk3: 'https://aka.doubaocdn.com/s/luJgikxm9M',
    walk4: 'https://aka.doubaocdn.com/s/A21pYqojQe',
    attack: 'https://aka.doubaocdn.com/s/fZ8bgNFydU',
    attack2: 'https://aka.doubaocdn.com/s/7PqulR5l5h',
    hit: 'https://aka.doubaocdn.com/s/bms44tYXFo',
    color: '#604080', glow: '#9060c0', useImg: true, multiFrame: true,
  },

};
